blog-site/playground/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_lists'),
    path('', views.posts_list, name='post_lists'),
    path('tag/<slug:tag_slug>', views.posts_list, name='post_lists_with_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share', view=views.post_share, name='post_share'),
    path('<int:post_id>/comment', view=views.add_comment, name='add_comment')
]

blog-site/storefront/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls),
path("blog/",include('playground.urls', namespace='blog'))]

blog-site/playground/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    tags = TaggableManager()
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='playground_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()  # the default manager
    published = PublishedManager()  # the custom manager

    class Meta:
        ordering = ["-publish"]
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,  related_name='comments')
    name = models.CharField(max_length=50)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=['created'])]

    def __str__(self) -> str:
        return f"coment by {self.name} on {self.post}"

blog-site/playground/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    to = forms.EmailField()
    comments = forms.CharField(widget=forms.Textarea, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']

blog-site/playground/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.core.mail import send_mail
from playground.forms import EmailPostForm, CommentForm
from .models import Post
from django.db.models import Count
from taggit.models import Tag
# Create your views here.


class PostListView(ListView):
    queryset = posts_list = Post.objects.all().filter(status=Post.Status.PUBLISHED)
    context_object_name = 'posts'
    paginate_by = 3
    template_name = "blog/post/list.html"


def post_share(request, post_id):
    sent = False
    post = get_object_or_404(Post, id=post_id)
    post_url = request.build_absolute_uri(post.get_absolute_url())

    if request.method == 'POST':
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            # send email
            subject = f"{cd['name']} recommends you to read {post.title}"
            message = f"Read {post.title} at {post_url}"

            send_mail(subject, message, 'tashfeen@ricult.com', [cd['to']],
                      )
            sent = True

    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html',
                  {"post": post, "form": form, "sent": sent})


def posts_list(request, tag_slug=None):
    posts_list = Post.objects.all().filter(status=Post.Status.PUBLISHED)
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts_list = posts_list.filter(tags__in=[tag])

    paginator = Paginator(posts_list, 3)
    page_num = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.page_num)
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                             publish__year=year, publish__month=month, publish__day=day, slug=post)

    comments = post.comments.filter(active=True)
    form = CommentForm()

    post_tag_ids = post.tags.values_list('id', flat=True)
    similer_posts = Post.published.filter(
        tags__in=post_tag_ids).exclude(id=post.id)
    similer_posts = similer_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post, "comments": comments, "form": form,
                                                     "similer_posts": similer_posts})


@require_POST
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment = None
    form = CommentForm(data=request.POST)

    if form.is_valid():

        comment = form.save(commit=False)

        comment.post = post
        comment.save()

    return render(request, 'blog/post/comment.html', {"post": post, "comment": comment, "form": form})

blog-site/playground/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
{% block content %}
{% endblock %}
</div>
<div id="sidebar">
<h2>My blog</h2>
<p>This is my blog.</p>
</div>
</body>
</html>

blog-site/playground/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block content %}
{% if comment %}
<h2>You comment has been added</h2>
<p> <a href="{{post.get_absolute_url}}">Back to Post</a> </p>

{% else %}
{% include "directory/comment_form.html" %}

{% endif %}


{% endblock  %}

blog-site/playground/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}

<p>
<a href="{% url "blog:post_share" post.id %}">
share this post
</a>
</p>


<h2>Similar posts</h2>
{% for post in similer_posts %}
<p>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

{%with comments.count as total_comments%}

<h2>{{total_comments}} comment{{total_comments|pluralize}}</h2>
{%endwith%}

{% for comment in comments %}
<div>
    <p>
        Comment {{forloop.counter}} by {{comment.name}}
    </p>
    {{comment.body|linebreaks}}
</div>
{%empty%}
<p>There are no comments</p>
{% endfor %}
{%include "directory/comment_form.html" %}

{% endblock %}

blog-site/playground/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{%block title%}My Blog {%endblock%}
{%block content%}

{% if tag %}
<p>Posts tagged with {{tag.name}}</p>
{% endif %}

{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
    {{ post.title }}
    </a>
</h2>
<h3>Tags:  </h3>
{% for tag in post.tags.all %}
<p>
    <a href="{% url "blog:post_lists_with_tag" tag.slug %}">
        {{tag.name}}
    </a>
</p>
{% if not forloop.last %}, {%endif%}
{%endfor%}
    <p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
    {{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{%include "directory/pagination.html" with page=posts %}
{% endblock %}

blog-site/playground/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{%block title%}Post Share{%endblock%}

{% block content %}

{% if sent %}
<h3>Email Has been sent successfully to {{form.cleaned_data.to}}</h3>
{%else%}

<h2>share this post {{post.title}} by email</h2>

<form method="post">

    {{form.as_p}}
    {% csrf_token %}
    <input type="submit", value="send email">
</form>
{% endif %}


{% endblock  %}

blog-site/playground/templates/directory/comment_form.html
<h2>Add a new Comment</h2>
<form action="{% url "blog:add_comment" post.id %}" method="post">
{{form.as_p}}
{% csrf_token %}
<p><input type="submit" value="Add comment"></p>
</form>

blog-site/playground/templates/directory/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>